version: "3"

services:
    app1:
        build: 
            context: ./app1
    app2:
        build: 
            context: ./app2

    nginx:
        build:
            context: ./nginx
        ports: 
            - "5010:80"
